name: sync with upstream

on:
  push:
    branches: [ master ]

  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          set -ex

          git config --global user.name  leleliu008
          git config --global user.email leleliu008@gmail.com
          git config pull.rebase true

          git remote add upstream https://git.savannah.gnu.org/git/config.git

          git pull upstream master:upstream-master

          git rebase upstream-master

          git push -f origin master
